import type { JourneySlide } from "@/components/ui/sequence-diagram"

export type JourneyKind = "Business" | "Technical"
export interface JourneyExample { id:string; title:string; kind:JourneyKind; industry:string; summary:string; command:string; slides:JourneySlide[] }

const slide=(id:string,title:string,caption:string,chart:string):JourneySlide=>({id,title,caption,chart:`sequenceDiagram\n${chart}`})

export const journeyCatalog: JourneyExample[] = [
  {id:"customer-onboarding",title:"Customer onboarding",kind:"Business",industry:"SaaS",summary:"Turn a signed contract into an activated, welcomed customer.",command:"Map an onboarding journey from signed contract through provisioning, training, and first value.",slides:[slide("handoff","Sales handoff","The account context moves from sales to success.","  participant S as Sales\n  participant C as Customer Success\n  participant A as Account\n  S->>C: Share goals and commitments\n  C->>A: Create onboarding plan"),slide("activate","Activation","The customer is provisioned and guided to first value.","  participant C as Customer\n  participant P as Product\n  participant T as Success Team\n  T->>P: Provision workspace\n  P-->>C: Invite team\n  C->>P: Complete first workflow")]},
  {id:"approval-chain",title:"Purchase approval",kind:"Business",industry:"Operations",summary:"Show policy checks, manager review, and finance approval.",command:"Design a purchase approval journey with thresholds, policy checks, finance review, and audit history.",slides:[slide("request","Request submitted","Operations captures the business need.","  actor E as Employee\n  participant O as Operations\n  E->>O: Submit purchase request\n  O-->>E: Validation complete"),slide("approve","Review and approve","The request follows the right approval path.","  participant O as Operations\n  participant M as Manager\n  participant F as Finance\n  O->>M: Request approval\n  M->>F: Approved within budget\n  F-->>O: Purchase authorized")]},
  {id:"support-escalation",title:"Support escalation",kind:"Business",industry:"Customer service",summary:"Move a complex issue from intake to engineering and resolution.",command:"Create a support escalation journey with triage, SLA risk, engineering handoff, and customer updates.",slides:[slide("triage","Triage","Support identifies severity and ownership.","  actor C as Customer\n  participant S as Support\n  C->>S: Report degraded service\n  S-->>C: Confirm priority and SLA"),slide("resolve","Engineering resolution","A verified fix returns through support.","  participant S as Support\n  participant E as Engineering\n  actor C as Customer\n  S->>E: Escalate with diagnostics\n  E-->>S: Fix deployed\n  S-->>C: Confirm resolution")]},
  {id:"hiring-loop",title:"Hiring loop",kind:"Business",industry:"People",summary:"Explain the path from application to structured decision.",command:"Map a fair hiring journey from application through interviews, scorecards, offer, and onboarding.",slides:[slide("screen","Candidate screen","Recruiting aligns candidate and role early.","  actor C as Candidate\n  participant R as Recruiter\n  participant H as Hiring Manager\n  C->>R: Submit application\n  R->>H: Share qualified profile"),slide("decision","Structured decision","Independent evidence becomes a clear decision.","  participant I as Interview Panel\n  participant H as Hiring Manager\n  actor C as Candidate\n  I->>H: Submit scorecards\n  H-->>C: Extend offer")]},
  {id:"order-fulfillment",title:"Order fulfillment",kind:"Business",industry:"Commerce",summary:"Trace an order from payment through warehouse dispatch.",command:"Create an order fulfillment journey covering payment, inventory reservation, picking, shipping, and delivery updates.",slides:[slide("order","Order accepted","Payment and stock are confirmed.","  actor C as Customer\n  participant O as Store\n  participant P as Payments\n  C->>O: Place order\n  O->>P: Authorize payment\n  P-->>O: Approved"),slide("ship","Pick and ship","The warehouse turns an order into a tracked parcel.","  participant O as Store\n  participant W as Warehouse\n  participant D as Carrier\n  O->>W: Release pick list\n  W->>D: Hand off parcel\n  D-->>O: Tracking active")]},
  {id:"patient-intake",title:"Patient intake",kind:"Business",industry:"Healthcare",summary:"Make a careful intake and clinician handoff visible.",command:"Map a privacy-aware patient intake journey from booking through forms, triage, and clinician handoff.",slides:[slide("intake","Digital intake","The patient provides the information needed for safe triage.","  actor P as Patient\n  participant I as Intake\n  participant N as Nurse\n  P->>I: Submit consent and symptoms\n  I->>N: Flag clinical context"),slide("visit","Prepared visit","The clinician receives a concise, verified handoff.","  participant N as Nurse\n  participant C as Clinician\n  actor P as Patient\n  N->>C: Share triage summary\n  C->>P: Begin informed consultation")]},
  {id:"auth-session",title:"Secure sign-in",kind:"Technical",industry:"Identity",summary:"Explain credentials, session creation, and protected access.",command:"Architect a secure email-password authentication flow with hashed credentials, server sessions, and protected routes.",slides:[slide("signin","Verify identity","Credentials are verified on the server.","  actor U as User\n  participant A as Auth Server\n  participant D as Database\n  U->>A: Submit credentials\n  A->>D: Read password hash\n  D-->>A: User record"),slide("session","Create session","A secure cookie carries the session reference.","  participant A as Auth Server\n  participant S as Session Store\n  actor U as User\n  A->>S: Create session\n  A-->>U: Set secure HTTP-only cookie")]},
  {id:"payment-checkout",title:"Reliable checkout",kind:"Technical",industry:"Payments",summary:"Separate checkout creation from webhook fulfillment.",command:"Architect an idempotent checkout with server-side price validation, hosted payment, signed webhooks, and fulfillment.",slides:[slide("checkout","Create checkout","The server owns pricing and checkout creation.","  actor U as Buyer\n  participant A as App Server\n  participant P as Payment Provider\n  U->>A: Start checkout\n  A->>P: Create idempotent session\n  P-->>U: Hosted checkout"),slide("fulfill","Webhook fulfillment","Signed events trigger durable fulfillment.","  participant P as Payment Provider\n  participant W as Webhook\n  participant O as Orders\n  P->>W: payment.completed\n  W->>O: Fulfill once\n  O-->>W: Recorded")]},
  {id:"queue-worker",title:"Durable job queue",kind:"Technical",industry:"Infrastructure",summary:"Decouple a request from slow background work.",command:"Design a durable job queue with idempotent producers, retries, dead-letter handling, and observable workers.",slides:[slide("enqueue","Accept quickly","The API validates and enqueues slow work.","  actor C as Client\n  participant A as API\n  participant Q as Queue\n  C->>A: Submit export\n  A->>Q: Enqueue job\n  A-->>C: 202 Accepted"),slide("work","Process reliably","A worker retries safely and stores the result.","  participant Q as Queue\n  participant W as Worker\n  participant S as Storage\n  Q->>W: Deliver job\n  W->>S: Store export\n  W-->>Q: Acknowledge")]},
  {id:"cache-aside",title:"Cache-aside read",kind:"Technical",industry:"Performance",summary:"Show cache miss, source read, and warm response.",command:"Explain a cache-aside architecture including key design, TTL, stampede control, and invalidation.",slides:[slide("miss","Cold read","The application falls back to its database.","  actor C as Client\n  participant A as API\n  participant R as Cache\n  participant D as Database\n  C->>A: GET /catalog\n  A->>R: GET catalog\n  R-->>A: Miss\n  A->>D: Query catalog"),slide("warm","Warm read","The next request is served from cache.","  participant A as API\n  participant R as Cache\n  actor C as Client\n  A->>R: SET catalog with TTL\n  C->>A: GET /catalog\n  A->>R: GET catalog\n  R-->>A: Hit")]}]
